SELECT A.AUTHOR_ID, A.AUTHOR_NAME, B.CATEGORY, B.SALES
FROM AUTHOR A
JOIN (SELECT BS.BOOK_ID, SUM(BS.SALES * B.PRICE) AS SALES, B.CATEGORY, B.AUTHOR_ID
    FROM BOOK_SALES BS
    JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
    WHERE BS.SALES_DATE LIKE '2022-01%'
    GROUP BY B.AUTHOR_ID, B.CATEGORY) B 
ON A.AUTHOR_ID = B.AUTHOR_ID
ORDER BY A.AUTHOR_ID, B.CATEGORY DESC
;

# <풀이>
# 2022-01 판매 데이터 중 카테고리 별, 저자 별로 각각 그룹 후 판매량 계산 후 join
