SELECT BOOK_ID, DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISHED_DATE
FROM BOOK
WHERE CATEGORY = '인문' AND LEFT(PUBLISHED_DATE, 4) = '2021'
ORDER BY PUBLISHED_DATE
;

-- <풀이>
-- 2021년만 뽑으려고 LEFT 사용, Format 맞추려고 DATE_FORMAT()
