SELECT B.CATEGORY, SUM(S.TOTAL_SALES) AS TOTAL_SALES
FROM BOOK B
JOIN (
    SELECT T.BOOK_ID, SUM(T.SALES) AS TOTAL_SALES
    FROM (SELECT * FROM BOOK_SALES  
            WHERE LEFT(SALES_DATE,7) = '2022-01') T
    GROUP BY T.BOOK_ID    
) S
ON B.BOOK_ID = S.BOOK_ID 
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY
;


# <풀이>
# 2022-01 만 뺀 TABLE에서 ID로 그룹화 후 SALE양 합 구한 뒤 join 후 다시 카테고리 별 그룹화
