SELECT PA.APNT_NO, PA.PT_NAME, PA.PT_NO, PA.MCDP_CD, D.DR_NAME, PA.APNT_YMD
FROM DOCTOR D
JOIN (SELECT MDDR_ID,A.APNT_NO, PT_NAME, A.PT_NO, MCDP_CD, APNT_YMD
    FROM APPOINTMENT A
    JOIN PATIENT P
    ON A.PT_NO = P.PT_NO
    WHERE APNT_YMD LIKE '2022-04-13%' AND APNT_CNCL_YN = 'N' and MCDP_CD = 'CS') PA
ON DR_ID = PA.MDDR_ID
ORDER BY PA.APNT_YMD
;

# <풀이>
# 그냥 JOIN 후 SELECT
