SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE BETWEEN '2022-08-00' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(*) >= 5
) AND START_DATE BETWEEN '2022-08-00' AND '2022-10-31'
GROUP BY CAR_ID, MONTH
HAVING RECORDS > 0
ORDER BY MONTH ASC, CAR_ID DESC
;

# <풀이>
# 서브 쿼리에서 CAR_ID로 그룹을 묶어 대여 시작일이 8월, 10월 사이인 COUNT 5이상인 애들을 구별해준다.
# WHERE 절에서 한번 더 날짜를 비교해주는데 해당하는 CAR_ID가 존재하는데 대여시작일이 다를 수 있어서 다시 비교해주는 것
# 이 부분에서 계속 오류 발생했었음
# CAR_ID, MONTH 그룹을 묶어서 1 이상인 부분만 출력해준다.
