SELECT DISTINCT A.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY A
JOIN (SELECT *
    FROM CAR_RENTAL_COMPANY_CAR
    WHERE CAR_TYPE = '세단') B
ON A.CAR_ID = B.CAR_ID
WHERE START_DATE LIKE '%-10-%'
ORDER BY A.CAR_ID DESC
;


# <풀이>
# 세단만 추린 테이블과 join 후 10월 대여 시작 중복 제거 후 출력
