SELECT HISTORY_ID, CAR_ID, DATE_FORMAT(START_DATE,'%Y-%m-%d') as START_DATE, DATE_FORMAT(END_DATE,'%Y-%m-%d') AS END_DATE,
CASE
    WHEN(datediff(END_DATE, START_DATE)+1 >= 30) THEN '장기 대여'
    ELSE '단기 대여'
END AS RENT_TYPE
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE START_DATE LIKE "2022-09-__"
ORDER BY HISTORY_ID DESC
;

# <풀이>
# DATE_FORMAT(START_DATE,'%Y-%m-%d') -> 형식 맞추기
# 조건부 CASE WHEN() THEN ELSE END 사용
