SELECT AB.CAR_ID, C.CAR_TYPE, ROUND(AB.DAILY_FEE * 30 * (100 - C.DISCOUNT_RATE) / 100) AS FEE
FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN C 
INNER JOIN (
    SELECT A.CAR_TYPE, A.CAR_ID, A.DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR A
    WHERE A.CAR_TYPE IN ('세단', 'SUV')
      AND NOT EXISTS (
            SELECT 1
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
            WHERE H.CAR_ID = A.CAR_ID AND H.END_DATE >= '2022-11-01' AND H.START_DATE <= '2022-11-30'
        )
) AB
    ON AB.CAR_TYPE = C.CAR_TYPE
WHERE C.DURATION_TYPE = '30일 이상'
HAVING FEE BETWEEN 500000 AND 1999999
ORDER BY FEE DESC, C.CAR_TYPE, AB.CAR_ID DESC;


# <풀이>
# 2022년 11월 1일부터 2022년 11월 30일까지 대여 가능한 구문을 해결못하여 참고
# NOT EXISTS 통해 해결

