SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN (SELECT FLAVOR, SUM(TOTAL_ORDER) AS JT
    FROM JULY
    GROUP BY FLAVOR) J
ON J.FLAVOR = F.FLAVOR
ORDER BY J.JT+TOTAL_ORDER DESC
LIMIT 3
;

-- <풀이>
-- 그룹 -> 외래키 -> LIMIT 3(상위 3개 행)
